"""add_admin_id_to_user_session

Revision ID: 66f22baabbfb
Revises: 8308e2efd193
Create Date: 2026-03-04 03:34:03.482903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f22baabbfb'
down_revision: Union[str, Sequence[str], None] = '8308e2efd193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_session', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.alter_column('user_session', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'user_session', 'admin', ['admin_id'], ['admin_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_session', type_='foreignkey')
    op.alter_column('user_session', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_session', 'admin_id')
    # ### end Alembic commands ###
